# Notebook Imports

In [1]:
import pandas as pd
import numpy as np

# Constants

In [227]:
TRAINING_DATA_FILE = 'D:/GitRepositories/MachineLearning/ML_Udemy_Courses/Complete_2019_DS_ML_Bootcamp/SpamData/02_Training/train-data.txt'
TEST_DATA_FILE = 'D:/GitRepositories/MachineLearning/ML_Udemy_Courses/Complete_2019_DS_ML_Bootcamp/SpamData/03_Testing/test-data.txt'

TOKEN_SPAM_PROB_FILE = 'D:/GitRepositories/MachineLearning/ML_Udemy_Courses/Complete_2019_DS_ML_Bootcamp/SpamData/03_Testing/prob-spam.txt'
TOKEN_HAM_PROB_FILE = 'D:/GitRepositories/MachineLearning/ML_Udemy_Courses/Complete_2019_DS_ML_Bootcamp/SpamData/03_Testing/prob-ham.txt'
TOKEN_ALL_PROB_FILE = 'D:/GitRepositories/MachineLearning/ML_Udemy_Courses/Complete_2019_DS_ML_Bootcamp/SpamData/03_Testing/prob-all-tokens.txt'

TEST_FEATURE_MATRIX_FILE = 'D:/GitRepositories/MachineLearning/ML_Udemy_Courses/Complete_2019_DS_ML_Bootcamp/SpamData/03_Testing/test-features.txt'
TEST_TARGET_FILE = 'D:/GitRepositories/MachineLearning/ML_Udemy_Courses/Complete_2019_DS_ML_Bootcamp/SpamData/03_Testing/test-target.txt'

VOCABULARY_SIZE = 2500

### Read and load features from .txt file into Numpy Array

In [3]:
sparse_train_data = np.loadtxt(TRAINING_DATA_FILE, delimiter=' ', dtype=int)

In [4]:
sparse_test_data = np.loadtxt(TEST_DATA_FILE, delimiter=' ', dtype=int)

In [5]:
sparse_train_data[:5]

array([[ 0,  2,  1,  1],
       [ 0,  3,  1,  2],
       [ 0,  4,  1,  1],
       [ 0,  7,  1,  3],
       [ 0, 11,  1,  1]])

In [6]:
sparse_train_data[-5:]

array([[5795, 2058,    0,    1],
       [5795, 2061,    0, 7350],
       [5795, 2280,    0,    1],
       [5795, 2353,    0,    1],
       [5795, 2427,    0,    1]])

In [7]:
sparse_test_data[:5]

array([[8, 2, 1, 1],
       [8, 3, 1, 4],
       [8, 4, 1, 2],
       [8, 5, 1, 1],
       [8, 6, 1, 2]])

In [8]:
len(sparse_train_data)

262374

In [9]:
len(sparse_test_data)

119348

In [10]:
sparse_test_data.shape

(119348, 4)

In [11]:
sparse_test_data.shape[0]

119348

In [12]:
sparse_test_data.shape[1]

4

In [13]:
# Fetching all the row data for the first column. i.e., the 'DOC_ID' column.
print(sparse_train_data[:, 0])
print(sparse_test_data[:, 0])

[   0    0    0 ... 5795 5795 5795]
[   8    8    8 ... 5793 5793 5793]


In [14]:
# Unique emails.
print(len(np.unique(sparse_train_data[:, 0])))
print(len(np.unique(sparse_test_data[:, 0])))

4057
1739


### Creating Empty Data Frame

In [15]:
column_names = ['DOC_ID', 'CATEGORY'] + list(range(0, VOCABULARY_SIZE))
column_names

['DOC_ID',
 'CATEGORY',
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,


In [16]:
print(len(sparse_test_data[:, 0]))
print(len(np.unique(sparse_test_data[:, 0])))

index_names = np.unique(sparse_test_data[:, 0])
index_names

119348
1739


array([   8,   12,   14, ..., 5788, 5792, 5793])

In [17]:
full_matrix_temp = pd.DataFrame(columns=column_names, index=index_names)
full_matrix_temp.fillna(0, inplace=True)
full_matrix_temp.DOC_ID = full_matrix_temp.index
full_matrix_temp.set_index('DOC_ID', inplace=True)
full_matrix_temp

CATEGORY  0  1  2  3  4  5  6  7  8  ...  2490  2491  2492  2493  \
DOC_ID                                       ...                           
8              0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
12             0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
14             0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
15             0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
17             0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
...          ... .. .. .. .. .. .. .. .. ..  ...   ...   ...   ...   ...   
5783           0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
5786           0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
5788           0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
5792           0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
5793           0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0   

        2494  2495  2496  2497  2498  2499  
DOC_ID                                      
8          0     0     0     0     0     0  
12         0     0     0     0     0     0  
14         0     0     0     0     0     0  
15         0     0     0     0     0     0  
17         0     0     0     0     0     0  
...      ...   ...   ...   ...   ...   ...  
5783       0     0     0     0     0     0  
5786       0     0     0     0     0     0  
5788       0     0     0     0     0     0  
5792       0     0     0     0     0     0  
5793       0     0     0     0     0     0  

[1739 rows x 2501 columns]

In [18]:
sparse_test_data.shape[0]

119348

In [19]:
sparse_test_data[119347]

array([5793, 2490,    0,    1])

### Creating Full Matrix

In [34]:
def make_full_matrix(sparse_matrix, nr_words, doc_idx=0, word_idx=1, cat_idx=2, freq_idx=3):
    
    column_names = ['DOC_ID', 'CATEGORY'] + list(range(0, nr_words))
    index_names = np.unique(sparse_matrix[:, 0])
    
    full_matrix_df = pd.DataFrame(columns=column_names, index=index_names)
    full_matrix_df.fillna(value=0, inplace=True)

    for i in range(0, sparse_matrix.shape[0]):
        doc_nr = sparse_matrix[i][doc_idx]
        word_id = sparse_matrix[i][word_idx]
        label = sparse_matrix[i][cat_idx]
        occurrence = sparse_matrix[i][freq_idx]
        
        full_matrix_df.at[doc_nr, 'DOC_ID'] = doc_nr
        full_matrix_df.at[doc_nr, 'CATEGORY'] = label
        full_matrix_df.at[doc_nr, word_id] = occurrence
        
        
    full_matrix_df.set_index('DOC_ID', inplace=True)
    
    return full_matrix_df
    

In [139]:
%%time
full_train_matrix = make_full_matrix(sparse_train_data, VOCABULARY_SIZE)
full_train_matrix.head()

Wall time: 8.6 s


CATEGORY  0  1  2  3  4  5  6   7  8  ...  2490  2491  2492  2493  \
DOC_ID                                        ...                           
0              1  0  0  1  2  1  0  0   3  0  ...     0     0     0     0   
1              1  7  1  2  0  1  0  0   1  0  ...     0     0     0     0   
2              1  6  1  1  0  1  0  0   1  0  ...     0     0     0     0   
3              1  6  0  0  2  4  0  3  13  0  ...     0     0     0     0   
4              1  5  1  2  0  1  0  0   1  0  ...     0     0     0     0   

        2494  2495  2496  2497  2498  2499  
DOC_ID                                      
0          0     0     0     0     0     0  
1          0     0     0     0     0     0  
2          0     0     0     0     0     0  
3          0     0     0     0     0     0  
4          0     0     0     0     0     0  

[5 rows x 2501 columns]

In [140]:
full_train_matrix.tail()

CATEGORY  0  1  2  3  4  5  6  7  8  ...  2490  2491  2492  2493  \
DOC_ID                                       ...                           
5789           0  3  1  0  1  0  0  0  1  0  ...     0     0     0     0   
5790           0  1  1  1  0  0  0  1  0  0  ...     0     0     0     0   
5791           0  3  1  0  1  1  0  0  0  1  ...     0     0     0     0   
5794           0  1  1  1  0  0  1  2  0  0  ...     0     0     0     0   
5795           0  3  4  2  0  5  0  3  0  0  ...     0     0     0     0   

        2494  2495  2496  2497  2498  2499  
DOC_ID                                      
5789       0     0     0     0     0     0  
5790       0     0     0     0     0     0  
5791       0     0     0     0     0     0  
5794       0     0     0     0     0     0  
5795       0     0     0     0     0     0  

[5 rows x 2501 columns]

## Training the Naive Bayes Model
### Calculating the Probability of Spam

In [141]:
# Challenge: Calculate the probability of spam - the percent of spam messages in the training dataset.
# Store this value in a variable called prob_spam.

print('Total number of emails:', len(full_train_matrix))
print('Total number of spam emails:', len(full_train_matrix[full_train_matrix.CATEGORY == 1]))

prob_spam = (len(full_train_matrix[full_train_matrix.CATEGORY == 1]) / len(full_train_matrix)) * 100
print('Percentage of spam emails:', prob_spam)

Total number of emails: 4057
Total number of spam emails: 1292
Percentage of spam emails: 31.84619176731575


### Calculating total number of Words.

In [142]:
full_train_matrix.shape

(4057, 2501)

In [144]:
# Expluding 'CATEGORY' and taking rest of the columns
full_train_features = full_train_matrix.iloc[:, full_train_matrix.columns != 'CATEGORY']
full_train_features.head()

0     1     2     3     4     5     6     7     8     9     ...  2490  \
DOC_ID                                                              ...         
0          0     0     1     2     1     0     0     3     0     0  ...     0   
1          7     1     2     0     1     0     0     1     0     0  ...     0   
2          6     1     1     0     1     0     0     1     0     0  ...     0   
3          6     0     0     2     4     0     3    13     0     0  ...     0   
4          5     1     2     0     1     0     0     1     0     0  ...     0   

        2491  2492  2493  2494  2495  2496  2497  2498  2499  
DOC_ID                                                        
0          0     0     0     0     0     0     0     0     0  
1          0     0     0     0     0     0     0     0     0  
2          0     0     0     0     0     0     0     0     0  
3          0     0     0     0     0     0     0     0     0  
4          0     0     0     0     0     0     0     0     0  

[5 rows x 2500 columns]

In [222]:
total_wc = full_train_features.sum().sum()
print('The total number of words in the emails are:', total_wc)

The total number of words in the emails are: 7209459


### Number of Tokens in Spam and Ham Emails

**Challenge**
1. Create a subset named 'spam_lengths', then count the total number of words that occur in spam emails
2. Also, create similar subset named 'ham_lengths', then count the total number of words that occur in ham emails.

In [179]:
# Calculating spam lengths.
spam_lengths = full_train_matrix[full_train_matrix.CATEGORY == 1]
spam_lengths.drop(columns=['CATEGORY'], inplace=True)
spam_wc = spam_lengths.sum().sum()
print('The total number of words in Spam emails are:', spam_wc)

The total number of words in Spam emails are: 3026901


In [180]:
# Calculating ham lengths.
ham_lengths = full_train_matrix[full_train_matrix.CATEGORY == 0]
ham_lengths.drop(columns=['CATEGORY'], inplace=True)
ham_wc = ham_lengths.sum().sum()
print('The total number of words in Ham emails are:', ham_wc)

The total number of words in Ham emails are: 4182558


In [181]:
spam_wc/spam_lengths.shape[0]

2342.8026315789475

In [182]:
ham_wc/ham_lengths.shape[0]

1512.679204339964

### Summing the Tokens Occuring in Spam

In [183]:
full_train_features.shape

(4057, 2500)

In [188]:
train_spam_tokens = full_train_features[full_train_matrix.CATEGORY == 1]
train_spam_tokens.head()

0     1     2     3     4     5     6     7     8     9     ...  2490  \
DOC_ID                                                              ...         
0          0     0     1     2     1     0     0     3     0     0  ...     0   
1          7     1     2     0     1     0     0     1     0     0  ...     0   
2          6     1     1     0     1     0     0     1     0     0  ...     0   
3          6     0     0     2     4     0     3    13     0     0  ...     0   
4          5     1     2     0     1     0     0     1     0     0  ...     0   

        2491  2492  2493  2494  2495  2496  2497  2498  2499  
DOC_ID                                                        
0          0     0     0     0     0     0     0     0     0  
1          0     0     0     0     0     0     0     0     0  
2          0     0     0     0     0     0     0     0     0  
3          0     0     0     0     0     0     0     0     0  
4          0     0     0     0     0     0     0     0     0  

[5 rows x 2500 columns]

In [189]:
train_spam_tokens.tail()

0     1     2     3     4     5     6     7     8     9     ...  2490  \
DOC_ID                                                              ...         
1885       1     0     0     2     0     1     0     0     0     0  ...     0   
1887       2     0     0     0     0     0     0     0     0     0  ...     0   
1889       0     0     0     0     0     0     0     0     1     0  ...     0   
1890       2     0     0     0     1     0     0     2     0     0  ...     0   
1895       1     1     1     0     0     0     0     0     0     0  ...     0   

        2491  2492  2493  2494  2495  2496  2497  2498  2499  
DOC_ID                                                        
1885       0     0     0     0     0     0     0     0     0  
1887       0     0     0     0     0     0     0     0     0  
1889       0     0     0     0     0     0     0     0     0  
1890       0     0     0     0     0     0     0     0     0  
1895       0     0     0     0     0     0     0     0     0  

[5 rows x 2500 columns]

In [190]:
train_spam_tokens.shape

(1292, 2500)

In [217]:
# Summing up all the columns.
summed_spam_tokens = train_spam_tokens.sum(axis=0) + 1 # 1 is added to avoid infinity in case if the result is 0 (Laplace Smoothing technique).
summed_spam_tokens.shape

(2500,)

In [200]:
summed_spam_tokens.head()

0    2177
1     936
2    1220
3    2026
4    1211
dtype: int64

In [201]:
summed_spam_tokens.tail()

2495    16
2496     7
2497    30
2498    12
2499     3
dtype: int64

### Summing the Token occuring in Ham

In [202]:
train_ham_tokens = full_train_features[full_train_matrix.CATEGORY == 0]
train_ham_tokens.head()

0     1     2     3     4     5     6     7     8     9     ...  2490  \
DOC_ID                                                              ...         
1896       1     2     1     0     1     1     2     0     1     1  ...     0   
1898       2     1     0     1     1     0     2     1     0     0  ...     0   
1899       2     1     1     0     0     1     1     0     1     0  ...     0   
1900       3     4     0     1     0     0     1     1     1     1  ...     0   
1901       2     2     0     1     0     0     1     1     0     0  ...     0   

        2491  2492  2493  2494  2495  2496  2497  2498  2499  
DOC_ID                                                        
1896       0     0     0     0     0     0     0     0     0  
1898       0     0     0     0     0     0     0     0     0  
1899       0     0     0     0     0     0     0     0     0  
1900       0     0     0     0     0     0     0     0     0  
1901       0     0     0     0     0     0     0     0     0  

[5 rows x 2500 columns]

In [203]:
train_ham_tokens.tail()

0     1     2     3     4     5     6     7     8     9     ...  2490  \
DOC_ID                                                              ...         
5789       3     1     0     1     0     0     0     1     0     0  ...     0   
5790       1     1     1     0     0     0     1     0     0     0  ...     0   
5791       3     1     0     1     1     0     0     0     1     0  ...     0   
5794       1     1     1     0     0     1     2     0     0     1  ...     0   
5795       3     4     2     0     5     0     3     0     0     4  ...     0   

        2491  2492  2493  2494  2495  2496  2497  2498  2499  
DOC_ID                                                        
5789       0     0     0     0     0     0     0     0     0  
5790       0     0     0     0     0     0     0     0     0  
5791       0     0     0     0     0     0     0     0     0  
5794       0     0     0     0     0     0     0     0     0  
5795       0     0     0     0     0     0     0     0     0  

[5 rows x 2500 columns]

In [204]:
train_ham_tokens.shape

(2765, 2500)

In [208]:
# Summing up all the columns.
summed_ham_tokens = train_ham_tokens.sum(axis=0) + 1
summed_ham_tokens.shape

(2500,)

In [209]:
summed_ham_tokens.head()

0    5483
1    2588
2    2044
3     938
4    1611
dtype: int64

In [206]:
summed_ham_tokens.tail()

2495    13
2496    25
2497     6
2498    19
2499    26
dtype: int64

### P(Token|Spam) - Probability that a Token Occurs given the Email is Spam

In [213]:
prob_tokens_spam = summed_spam_tokens / (spam_wc + VOCABULARY_SIZE)
prob_tokens_spam[:5]

0    0.000719
1    0.000309
2    0.000403
3    0.000669
4    0.000400
dtype: float64

In [214]:
prob_tokens_spam.sum()

1.0

### P(Token|Ham) - Probability that a Token Occurs given the Email is Ham

In [215]:
prob_tokens_ham = summed_ham_tokens / (ham_wc + VOCABULARY_SIZE)
prob_tokens_ham[:5]

0    0.001310
1    0.000618
2    0.000488
3    0.000224
4    0.000385
dtype: float64

In [216]:
prob_tokens_ham.sum()

1.0

### P(Token) -  Probability of Token Occurs

In [223]:
prob_tokens_all = full_train_features.sum(axis=0) / (total_wc)
prob_tokens_all.sum()

1.0

### Save the Trained Model

In [226]:
np.savetxt(TOKEN_SPAM_PROB_FILE, prob_tokens_spam)
np.savetxt(TOKEN_HAM_PROB_FILE, prob_tokens_ham)
np.savetxt(TOKEN_ALL_PROB_FILE, prob_tokens_all)

### Prepare test data

***Challenge:*** Create a full matrix from the full_test_matrix. Time the function call. How long does it take? Separate the features and the target values. Save these as separate .txt files: a TEST_FEATURE_MATRIX_FILE and a TEST_TARGET_FILE file.

In [261]:
%%time
full_test_matrix = make_full_matrix(sparse_test_data, nr_words=VOCABULARY_SIZE)
full_test_matrix.head()

Wall time: 4.76 s


CATEGORY  0  1  2  3  4  5  6  7  8  ...  2490  2491  2492  2493  \
DOC_ID                                       ...                           
8              1  0  0  1  4  2  1  2  4  1  ...     0     0     0     0   
12             1  6  1  1  0  1  0  0  1  0  ...     0     0     0     0   
14             1  0  0  1  1  0  0  0  0  0  ...     0     0     0     0   
15             1  0  2  1  1  2  0  0  3  0  ...     0     0     0     0   
17             1  0  0  0  0  1  0  1  0  0  ...     0     0     0     0   

        2494  2495  2496  2497  2498  2499  
DOC_ID                                      
8          0     0     0     0     0     0  
12         0     0     0     0     0     0  
14         0     0     0     0     0     0  
15         0     0     0     0     0     0  
17         0     0     0     0     0     0  

[5 rows x 2501 columns]

In [229]:
full_test_matrix.tail()

CATEGORY  0  1  2  3  4  5  6  7  8  ...  2490  2491  2492  2493  \
DOC_ID                                       ...                           
5783           0  2  1  0  2  0  0  0  0  0  ...     0     0     0     0   
5786           0  5  5  2  2  1  2  0  0  1  ...     0     0     0     0   
5788           0  0  4  0  2  4  3  3  1  4  ...     0     0     0     0   
5792           0  2  2  0  1  0  0  2  1  0  ...     0     0     0     0   
5793           0  1  9  1  0  0  1  2  1  1  ...     1     0     0     0   

        2494  2495  2496  2497  2498  2499  
DOC_ID                                      
5783       0     0     0     0     0     0  
5786       0     0     0     0     0     0  
5788       0     0     0     0     0     0  
5792       0     0     0     0     0     0  
5793       0     0     0     0     0     0  

[5 rows x 2501 columns]

In [230]:
test_features = full_test_matrix.drop(columns=['CATEGORY'])
test_features.head()

0     1     2     3     4     5     6     7     8     9     ...  2490  \
DOC_ID                                                              ...         
8          0     0     1     4     2     1     2     4     1     2  ...     0   
12         6     1     1     0     1     0     0     1     0     0  ...     0   
14         0     0     1     1     0     0     0     0     0     0  ...     0   
15         0     2     1     1     2     0     0     3     0     4  ...     0   
17         0     0     0     0     1     0     1     0     0     0  ...     0   

        2491  2492  2493  2494  2495  2496  2497  2498  2499  
DOC_ID                                                        
8          0     0     0     0     0     0     0     0     0  
12         0     0     0     0     0     0     0     0     0  
14         0     0     0     0     0     0     0     0     0  
15         0     0     0     0     0     0     0     0     0  
17         0     0     0     0     0     0     0     0     0  

[5 rows x 2500 columns]

In [258]:
test_target = full_test_matrix[['CATEGORY']]
test_target.head()

CATEGORY
DOC_ID          
8              1
12             1
14             1
15             1
17             1

In [259]:
test_target.shape

(1739, 1)

In [260]:
np.savetxt(TEST_FEATURE_MATRIX_FILE, test_features)
np.savetxt(TEST_TARGET_FILE, test_target)