In [1]:
# import 'numpy' library
import numpy as np

In [2]:
# Creating a simple (one-dimensional) array
x = np.array([1,4,6,7,8])

In [3]:
x

array([1, 4, 6, 7, 8])

In [5]:
# Type of array
type(x)

numpy.ndarray

In [6]:
# Getting array dimension.
x.ndim

1

In [7]:
# Getting shape of an array, i.e., nothing but the length of the array.
x.shape
# The output give you array size followed by ', ' indicating its a single dimensional array

(5,)

In [8]:
# Size of an array
x.size

5

In [9]:
# Array datatype
x.dtype

dtype('int32')

In [12]:
# Displaying array content for a specified index
x[3,]

7

In [15]:
# Displaying array elements uptil specified index
x[:3]

array([1, 4, 6])

In [16]:
# Saves the array elements into the specified file name with extension '.npy' under the current working directory
np.save('numpy_manip', x)

In [25]:
# Loads the specified file from the current working directory
y = np.load("numpy_manip.npy")
y

array([1, 4, 6, 7, 8])